#! /bin/sh

pkill sxhkd
sxhkd &

#--wallpaper_aleatorio--#
/home/angell/Imágenes/.wallpaper/random.sh

setxkbmap latam
xrandr -s 1366x768  -r 60.00

pgrep -x sxhkd > /dev/null || sxhkd &

# nitrogen --restore &
picom -f &
polybar example &
# /home/angell/.eww/target/release/eww daemon &

bspc rule -a Zathura state=tiled

bspc monitor -d I II III IV V IV 

bspc config border_width               2
bspc config window_gap                 12
bspc config focused_border_color      '#61ffaf'
bspc config normal_border_color       '#000000'
bspc config active_border_color       '#ffffff'
bspc config presel_feedback_color     "#373737"

bspc config top_padding     1 
bspc config bottom_padding  1 
bspc config left_padding    1 
bspc config right_padding   1

bspc config split_ratio               0.52
bspc config borderless_monocle        false
bspc config gapless_monocle           true
bspc config focus_by_distance         true
bspc config history_aware_focus       true
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true
bspc config click_to_focus            true
bspc config pointer_follows_focus     false
bspc config pointer_follows_monitor   true


#-------------Confing_windows_float----------------#

# xprop | grep WM_CLASS  # con este comando en la terminal se ve la <nombre_de_clase>:<nombre_de_instancia>
# bspc rule -a <nombre_de_clase>:<nombre_de_instancia> state=floating
bspc rule -a matplotlib:matplotlib state=floating
bspc rule -a tk:Tk state=floating


#--------Confing_areas_de_trabajo_float------------#
bspc rule -a '*' state=floating desktop=^3
bspc rule -a '*' state=floating desktop=^4


# Agregar configuración de xss-lock con i3lock
# xss-lock i3lock &

