#!/bin/sh

# Detener y reiniciar sxhkd
pkill sxhkd
sxhkd &

# Establecer el fondo de pantalla aleatorio
/home/angell/Imágenes/.wallpaper/random.sh

# Establecer el diseño del teclado
setxkbmap latam

# Establecer la resolución de la pantalla
xrandr -s 1366x768 -r 60.00

# Reiniciar sxhkd si no está en ejecución
pgrep -x sxhkd > /dev/null || sxhkd &

# Iniciar picom para efectos de transparencia
picom -f &

# Iniciar la barra de estado Polybar
polybar example &

# Configuración de BSPWM
bspc monitor -d 1 2 3 4 5 6 

bspc config border_width               2
bspc config window_gap                 12
bspc config focused_border_color      '#61ffaf'
bspc config normal_border_color       '#000000'
bspc config active_border_color       '#ffffff'
bspc config presel_feedback_color     "#373737"

bspc config top_padding     1 
bspc config bottom_padding  1 
bspc config left_padding    1 
bspc config right_padding   1

bspc config split_ratio               0.52
bspc config borderless_monocle        false
bspc config gapless_monocle           true
bspc config focus_by_distance         true
bspc config history_aware_focus       true
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true
bspc config click_to_focus            true
bspc config pointer_follows_focus     false
bspc config pointer_follows_monitor   true

# Regla para abrir cualquier ventana en el escritorio actual si no tiene otro definido
# bspc rule -a '*' desktop='focused' state=tiled

# Regla para aplicaciones tiled en fullscreen
bspc rule -a kitty state=fullscreen

# Regla para aplicaciones tiled en Zathura
bspc rule -a Zathura state=tiled

# Regla para aplicaciones tiled en floating
bspc rule -a matplotlib state=floating
bspc rule -a Mathematica state=floating
bspc rule -a Tk state=floating

# Reglas para asignar aplicaciones a escritorios específicos
bspc rule -a kitty desktop=^1
bspc rule -a Zathura desktop=^2
bspc rule -a matplotlib desktop=^3
bspc rule -a Mathematica desktop=^3
bspc rule -a Tk desktop=^3
bspc rule -a Com.github.xournalpp.xournalpp desktop=^4
bspc rule -a org.gnome.Nautilus desktop=^4
bspc rule -a feh desktop=^5
bspc rule -a discord desktop=^5
bspc rule -a Brave-browser desktop=^6

# xprop | grep WM_CLASS  # con este comando en la terminal se ve la <nombre_de_clase>:<nombre_de_instancia>
# bspc rule -a <nombre_de_clase>:<nombre_de_instancia> state=floating
# bspc rule -a matplotlib:matplotlib state=floating
# bspc rule -a tk:Tk state=floating

